### ISSUE TITLE
At  Project Page, the "Submit a Project" button doesn't match with the UI.

### ISSUE THREAD

**Issue by negi-sachin** [dsc-gtbit/DSC-Official-Website#15]
It should be similar to the blue button in footer.

**Comment by AarambhVerma** [comment]
@negi-sachin can I improve that?

**Comment by negi-sachin** [comment]
@AarambhVerma sure.

**Comment by KushalBhanot** [comment]
Hey! I can fix this.

**Comment by saranraj48** [comment]
Hey!
I have change the button style in project page.

**Comment by githubANURAG1** [comment]
Hi, I want to do this could you please assign it to me
